disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - multiple_closures_with_trailing_closure
  - identifier_name
  - function_parameter_count

line_length:
    warning: 100
    error: 120
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
